spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/selldb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true

  jpa:
    show-sql: true
#    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database: mysql
#        database-platform: org.hibernate.dialect.MySQLDialect
#        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
#  port: 8086

#wechat:
#  mpAppId: wxb5ab90f0c8d1189f
#  mpAppSecret: 8bdf6a68df39b47215200afd08d598cd
#  mchId: 1533769421
#  mchKey: a2RhZ2trb28wMTAzMjk0MTlrM2prYWtr
#  keyPath: D:\mysite\weixin_cert\apiclient_cert.p12
#  notifyUrl:  http://exp.mynatapp.cc/sell/pay/notify

#测试号
wechat:
  mpAppId: wxd85bb7b0967aaf64
  mpAppSecret: 0846215c63c1a9a982819c71e2387b72
#  mchId: 1533769421
#  mchKey: a2RhZ2trb28wMTAzMjk0MTlrM2prYWtr
#  keyPath: D:\mysite\weixin_cert\apiclient_cert.p12
#  notifyUrl:  http://p582pc.natappfree.cc/sell/pay/notify

debug: true
